### ISSUE TITLE
Swift 4?

### ISSUE THREAD

**Issue by Maxnelson997** [Vaberer/Font-Awesome-Swift#89]
Im getting a lot of syntax errors after migrating to Swift 4 and Xcode 9.

**Comment by Maxnelson997** [comment]
I went through and fixed them

**Comment by wattnpapa** [comment]
@Maxnelson997 do you have already a solution?

**Comment by moonvader** [comment]
same problem - any news about Swift 4 and Xcode 9 support?

**Comment by Maxnelson997** [comment]
Ah dang I really wanted to contribute... I should have hopped on this the day I fixed it.. :(

**Comment by TCOA** [comment]
I tried going through and fixing them, but not all had a 'Fix' button and I would rather not have to go figure out what to do, so I would really appreciate seeing a new version as quickly as possible (I'm on the last strings of getting my app out and actually flying in tonight to see the 'principals', so doing the update is pretty important!)

**Comment by rlam3** [comment]
@Vaberer ? Please help us by merging the swift 4 fix and create a new release. Thanks !

<img width="381" alt="screen shot 2017-09-30 at 8 16 37 am" src="https://user-images.githubusercontent.com/1154044/31046065-b8483d58-a5b7-11e7-97f0-f7e07ecf64b7.png">

**Comment by Vaberer** [comment]
Hello, update the pod to 1.7.0 Thanks for your patience. If there is sth urgent in the future, contact me at patrik@toptal.com

**Comment by edasque** [comment]
I still get those errors on Xcode 9.1 with 1.7.1. Any idea?

<img width="264" alt="jsondecodable_swift" src="https://user-images.githubusercontent.com/219187/32705438-5780c06a-c7e2-11e7-9e0a-36eadd62bdc1.png">

**Comment by rbudiharso** [comment]
Same here, any updates on this?

**Comment by TCOA** [comment]
works fine for me.......

` pod 'Font-Awesome-Swift', '~> 1.7.0'`

be sure to do pod update before pod install - then Swift Language Version of 4.0 works (compiles with no Font-Awesome-Swift errors)
